
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
{{- if .Values.oidc.enabled }}
  keycloak.json: |
    {
      "realm": "{{ .Values.oidc.config.realm }}",
      "auth-server-url": "{{ .Values.oidc.config.authServerUrl }}",
      "ssl-required": "external",
      "resource": "{{ .Values.oidc.config.clientId }}",
      "verify-token-audience": true,
      "public-client": true,
      "use-resource-role-mappings": true,
      "confidential-port": 0
    }
{{- end }}
  config.json: |
    {
        "backend_url_api": "{{ .Values.config.backendUrlApi }}",
        "websocket_url": "{{ .Values.config.websocketUrl }}"
    }